### PR TITLE
display artworks of 1st collection in front page

### PR DESCRIPTION
**Pull request by GiangNguyen1207**

### CODE REVIEW

**Comment by GiangNguyen1207** [comment]
@thuymymai can you check this branch if you can see the picture on the front page?

**Comment by thuymymai** [comment]
can not see picture lol

**Comment by GiangNguyen1207** [comment]
okay :(

**Comment by GiangNguyen1207** [comment]
let's leave it for until the end, when we push another version to server. We can check then if we see the images 👯

**Pull request merged**
